### PR TITLE
push from pootle plus updated POT file

### PR DESCRIPTION
**Pull request by quozl**
* push from pootle, split into message changes (1b23b57) and mechanical changes (9699c10),
 * a regenerated POT file (0f1fe55), attn @leonardcj.

### CODE REVIEW

**Comment by leonardcj** [comment]
Posted new POT to Pootle.  Updating languages from templates.  Will hopefully be landing refreshed PO files soon.  https://translate.sugarlabs.org/projects/Paint/

**Comment by quozl** [comment]
@leonardcj, thanks, reviewed and added as b42d924.

There is uncontrolled breeding of repeating headers; es.po has 38 of them, de.po has 13, is this expected?

Method to find;

```bash
grep -c "Copyright (C)" *.po | \
    tr ':' ' ' | awk '{print $2, $1}'|sort -rn | less
```

Repeating header;

```
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
```

**Comment by leonardcj** [comment]
I'll do a manual trim of headers when pushing completed PO files.  I think it is an old issue from a previous Pootle version update process back when it was semi-automagical.  I don't think we are currently experiencing header expansion.

**Comment by quozl** [comment]
Agreed, there _was_ uncontrolled breeding, but it isn't happening now.

**Pull request merged**
