### PR TITLE
Many PO files refresh

### PR DESCRIPTION
**Pull request by leonardcj**
Also trimmed headers

### CODE REVIEW

**Comment by quozl** [comment]
Thanks, some good stuff there, but some problems, sorry.  In comparing my `2017-048-po` branch b42d924fc64e5fbf26b7692172b3b35bbcb22a6f against your `master` branch at 3e135ffeb7c8407da7cd00cd9e0ddcccea9a8f92;

 * po/am.po POT-Creation-Date has regressed from 2017 to 2013,
 * po/ayc.po POT-Creation-Date has regressed from 2017 to 2015,
 * po/de.po po/el.po po/es.po po/it.po po/ja.po po/bl.po po/pt_BR.po po/quz.po po/sq.po POT-Creation-Date has regressed,
 * files have been committed with DOS line endings, which while they have no effect and can be stripped, might not be what you had intended.

Please fix the POT-Creation-Date regressions and commit.  Then after review I'll merge your changes with my branch, strip the DOS line endings, and update my pull request #20.

Also, suggest you avoid using your own `master` branch in future, as it can cause you problems.  See [branching](https://developer.sugarlabs.org/contributing.md.html#branching) in our guide to contributing.

**Comment by leonardcj** [comment]
Would it be easier if I closed this request and just started over again.  I did switch to using a Win10 machine as my old Linux box was misbehaving and that was obviously a mistake.  I obviously need to go back and review this activity's PO dir from top-to bottom.

**Comment by quozl** [comment]
It doesn't matter either way.  I'd rather not lose these changes so far, as they are good progress.  But I have a copy of them now if you want to start over.  I've made a commit on my branch from them, see 77b65de1dfaaf02f0f471e33c64fc7f3b2103871, omitting the files that had POT-Creation-Date regressions.

**Comment by quozl** [comment]
https://github.com/sugarlabs/paint-activity/pull/20 was merged which included the agreed parts of this pull request; please update your master, branch, and try the next refresh of translations?

**Comment by leonardcj** [comment]
Will redo the Paint PO file upload.

**Comment by quozl** [comment]
Thanks.  I've a yet to be pushed update of the POT file but there are no material changes in it apart from reordering.  I'm looking through the PO changes in preparation for your upload.

**Comment by leonardcj** [comment]
See new upload in pull request

https://github.com/sugarlabs/paint-activity/pull/25

**Pull request closed without merging**
