### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by vish-321**
please take a look at  it .

### CODE REVIEW

**Comment by quozl** [comment]
Welcome.  Thanks.  Reviewed.

* [ ] actually, _Paint is not part of the Sugar Desktop but is often included_ (see [a list of Fructose activities](http://download.sugarlabs.org/sources/sucrose/fructose/) that are part of the Sugar Desktop, see [this common wording](https://github.com/sugarlabs/clock-activity/blob/master/README.md)),
* [ ] the user guide for Paint should be https://help.sugarlabs.org/en/paint.html which is maintained in https://github.com/sugarlabs/help-activity/blob/master/source/paint.rst and it would be better to have that maintained than use the Wiki link you've used,
* [ ] the paragraph "Start a new project" has punctuation and spacing mistakes, and doesn't read well.

Also, your commit message does not meet [our conventions](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits).  It may be that you are using GitHub editor to prepare the file, which offers the default commit message "Create FILENAME".

Also, it seems you have not joined our [developer mailing list](http://lists.sugarlabs.org/listinfo/sugar-devel).  Please consider joining and reviewing archive of recent discussions.

Hope that helps!

**Comment by vish-321** [comment]
@quozl thanks. I've corrected points you mentioned, please review.

**Review by JuiP — COMMENTED** [review]
I suggest to squash the two commits. Also, consider rewording your commit message according to the coding conventions.

**Comment by quozl** [comment]
Squashed, reworded commit message as requested, removed documentation about how to use Sugar, fix language specific link to help.sugarlabs.org, and make text more like other README.md files we have.

**Comment by vish-321** [comment]
@JuiP @quozl  Thanks, This is helpful. Can it be merged ?

**Comment by quozl** [comment]
If I were your only correspondent on the pull request, I would have merged already.  But as @JuiP has spoken, I'm obliged to let her have her say first.

**Comment by JuiP** [comment]
@quozl Thanks! Looks good to merge!

**Comment by vish-321** [comment]
Thanks @quozl, @JuiP.  @quozl  I think it can be merged now.

**Pull request merged**
